### ISSUE TITLE
Problem compilation

### ISSUE THREAD

**Issue by profesoratecno** [OttoDIY/PLUS#10]
Hey, my name is Profesoratecno and I have a problem with compilation ZOWI BASE v2:

'EEPROM' was not declared in this scope

Arduino: 1.5.6-r2 (Windows 8), Placa:"Arduino Nano, ATmega328"

In file included from ZOWI_BASE_v2_MATRIX.ino:35:
C:\Users\profesoratecno\Documents\Arduino\libraries\Zowi/Zowi.h:98: error: 'LedMatrix' does not name a type
C:\Users\profesoratecno\Documents\Arduino\libraries\Zowi/Zowi.h:100: error: 'Oscillator' does not name a type
ZOWI_BASE_v2_MATRIX.ino: In function 'void setup()':
ZOWI_BASE_v2_MATRIX:202: error: 'EEPROM' was not declared in this scope
ZOWI_BASE_v2_MATRIX.ino: In function 'void receiveName()':
ZOWI_BASE_v2_MATRIX:934: error: 'EEPROM' was not declared in this scope
ZOWI_BASE_v2_MATRIX.ino: In function 'void requestName()':
ZOWI_BASE_v2_MATRIX:957: error: 'EEPROM' was not declared in this scope

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by cparrapa** [comment]
Hi Profesoratecno
This problem comes from Zowi code ;(, hoping for a Otto builder to help us fix it :S

**Comment by JoeyFitzp** [comment]
Profesoratecno,
Try using Arduino 1.6.9 to compile the code.  That's what I used to get  ZOWI_BASE_v2_MATRIX.ino to compile without errors

**Comment by cparrapa** [comment]
code replaced for our own APP

**Comment by julchung** [comment]
Hey, my name is Profesoratecno and I have a problem with using OttoDIYAPP_121.ino

when i use the library in ottodiy/plus/library   
it retures "  'EEPROM' was not declared in this scope"
but when i use the library in ottodiy/plus/app/ottodiyapp_121.zip.... /Librarys
it can upload to my arduino, but my otto can't work any more 
Arduino: 1.8.2 (Windows 10),"Arduino Nano, ATmega328"

**Comment by julchung** [comment]
sorry, I have a problem with bluetooth connect,in your code "otto.h" it define BT_RX  6 and BT_TX  7,but in the pdf flie, the picture show that BT_TX to pin 6 ,WHY? thankyou

**Comment by cparrapa** [comment]
can be a mistake can you pull a change request?

**Comment by cparrapa** [comment]
solved please check the updated codes
