### ISSUE TITLE
OttoDIYAPP_121.ino 'EEPROM' was not declared in this scope

### ISSUE THREAD

**Issue by remix1984** [OttoDIY/PLUS#11]
I fight with this second day... without luck
my bluetooth (hc06) doesn't change name to ZOWI
and ardu code doesnt compile 
783: error: 'EEPROM' was not declared in this scope

and first line  "sure" is to delete?? or comment...
Is there a Step by Step guide for actual otto?
i find that buzzer is connected to 13pin but in mine i have connected to 10

**Comment by cparrapa** [comment]
you need to download the latest Arduino IDE
no need to setup bletooth anymore just use our APP
instructions also updated
