### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Almax95** [OttoDIY/PLUS#14]
I tried to verify OttoDIYAPP_122_badudrate9600 . But I got this error " exit status 1 'requestRGB' was not declared in this scope " Pls help me..

**Comment by cparrapa** [comment]
oh really? @jarsoftelectrical do you know something about this?

**Comment by Almax95** [comment]
Though i wasn't fix any LED to the hardware . Is this concern ?

**Comment by Almax95** [comment]
Help !!! T_T

**Comment by Almax95** [comment]
Sorry to bother u again , I just downloaded zip file and tried to compile . I was facing an warning : " Sketch too big , see http://www.arduino.cc/en/Guide/ Troubleshooting#size for tips... " " " 
So I went to that link and found nth .. it was said to delete unnecessary one . So I delete the All of ABOVE #include < BatReader.h> ( necessary code ) and tried to verify .. but showed the same error... Any Method .. pls
I was using Arduino Nano with shield . 😢😢

**Comment by jarsoftelectrical** [comment]
[https://github.com/jarsoftelectrical/Otto-Libraries](url)
Please remove all libraries and sketches you have, remove them from the arduino libs folders completely and anywhere else you have downloaded them too.
Download the all the libraries again this time from the link above, and also the sketch from the link above, try to compile again.

**Comment by Almax95** [comment]
404 page not found .... a new link Pls

**Comment by Almax95** [comment]
I feel so sry to bother u again , I got new error : 

Property line    ' 
Error compiling for board arduino nano . 😥

**Comment by jarsoftelectrical** [comment]
The error is only a warning to inform you that you are using up most of the available memory that the Nano has, this can be ignored completely.

The 'error while uploading' is your problem, it has compiled correctly but has not sucessfully uploaded, you need to check your USB lead, the com port is set correctly, the Nano is a good Nano, the board is selected correctly ( Nano for Nano, Uno for Uno), the correct USB driver has been installed for the Nano clones
The problem is not a sketch or library problem now, it is a communication uploading problem.

**Comment by Almax95** [comment]
Thank you so much for your time 😃 . 

I close Arduino and open to make sure that the sketch file is completely done compiling again.... but ... so sry I got this error again : 

Property line   '
Error compiling for board arduino nano 😣 

Can u pls help me one more time !!!!

**Comment by Almax95** [comment]
I think I got this..... 
So thankful for your precious time... 
I appreciate your suggestion 💖 
Thank u so much again

**Comment by jarsoftelectrical** [comment]
No problem
Make sure you join the facebook group for more help and ideas as well any further advice / support
there are over 1000 members.
Share your design and experiences with the group.

**Comment by Almax95** [comment]
Can u just provide me link to FB ? 
There are so many gp named GitHub .
Is that GitHub Blockchain Developers Community ?

**Comment by jarsoftelectrical** [comment]
It is a closed group on Facebook, search facebook for 'Otto builders' you will see the blue Otto icon, and ask to join the group, answer the basic questions.

**Comment by GrimorJander** [comment]
"requestRGB' was not declared in this scope " = Bad Library

"An error occured while uploading the sketch " = With Arduino  Nano, you need to unplug bluetooth module in order to upload sketch
