### ISSUE TITLE
This isn't not an issue but request. 

### ISSUE THREAD

**Issue by Almax95** [OttoDIY/PLUS#17]
Hello sir , is there any code that the touch sensor change the robot functions such as walking ( avoiding obstacles)  , dancing ( soundsensor includes) , etc . 

Not with the Bluetooth Control Only one ( android apk includes )  😁 thx q sir ..

**Comment by GrimorJander** [comment]
V3.ino from davor

**Comment by Almax95** [comment]
Can I get link to it ? 😁😁😁😁 thx sir

**Comment by GrimorJander** [comment]
https://github.com/dlevstek/Otto

**Comment by Almax95** [comment]
Thx q so much sir 😃😃
