### ISSUE TITLE
issue not issue

### ISSUE THREAD

**Issue by Almax95** [OttoDIY/PLUS#18]
Hi , my otto work smoothly with Criminal Dance , touch sensor test , and ultrasonic sensor test. 
but when it come to " OTTO_NEW_OTTO_APP_9600 " ( bluetooth control ) , it doesn't move at all . Bluetooth is well connected and program is well uploaded (baud 9600) . but i got only " 2 " touch sensor . is that because of only 2 Touch Sensor ? or i don't know why . If i was not wrong , i think the code is also aimed for automatic ( don't require BT , only touch ) . But Touch sensors also don't work .

2 Touch Sensor - A1 A2 pin 
BT - RX TX GND VIN pin .

pls help !!!!!!!!!!

**Comment by cparrapa** [comment]
Hi Almax
Otto APP will work even without sensors so just give a try again, we just updated the codes and fixed bugs
OttoDIYAPP_125.ino
