### ISSUE TITLE
OttoDIYAPP_122.ino Not Compiling

### ISSUE THREAD

**Issue by EStClair** [OttoDIY/PLUS#19]
Im working on getting my OTTO to be able to work via bluetooth commands from my phone and can't seem to compile OttoDIYAPP_122.ino in codebender. I get the following:

> You tried to include one or more header files in your code using the wrong include statement. top_defs.h, util.h exist(s) in your project. 

Double quotes (#include "header.h") should be used instead of angles (#include <header.h>) for such headers.Read more

(sketch file) util.c:30:10: error: 'top_defs.h' file not found with <angled> include; use "quotes" instead

#include <top_defs.h>
         ^~~~~~~~~~~~
         "top_defs.h"

(sketch file) util.c:31:10: error: 'util.h' file not found with <angled> include; use "quotes" instead

#include <util.h>
         ^~~~~~~~
         "util.h"

In file included from (sketch file) util.c:31:
(sketch file) util.h:32:10: fatal error: 'wl_api.h' file not found

#include <wl_api.h>
         ^

**Comment by cparrapa** [comment]
updated to OttoDIYAPP_125.ino
