### ISSUE TITLE
stray '\302' in program

### ISSUE THREAD

**Issue by EddieMontana** [OttoDIY/PLUS#20]
My issue is more general and does not refer to one code in particular, but rather to a multitude of codes as they relate to download issues. Basically every single time I download from github.com an .ino file for Otto and try to compile it I get an error saying stray '\302' in program. That's not an exaggeration... every single one. My fix so far has always been to copy the actual code from the .ino file on the website and paste it and replace all the text in the Arduino window. That appears to work and the codes compile. 

However, my fear is that other files that I copy from the website including library files .h and .cpp may also be corrupted the same way during download, and I'm not sure if that's the case or not. Lately I've been getting errors that I haven't seen before. For example while trying to compile codes Otto_Adivinawi_v3.ino or Otto_Alarm_v3.ino under OttoPLUS I get an error saying "Error compiling for board Arduino Nano". I don't know if an error with a library could generate such an error.

So far I've been downloading the files by right-clicking on the file and selecting "Save Link As" from the drop-down... that refers to all file types including .ino  .h  .cpp.  Is there another, better way to download the .ino files or library files? Is there any way you could make under OttoPLUS a zip file with all the updated libraries and another zip file with the updated .ino codes? Maybe in a zip folder the files will be better preserved during download to avoid issues like the ones described. Thank you.

**Comment by cparrapa** [comment]
Hi Eddie
Let's divide an conquer:
1. If github is giving us trouble then we should report this an issue of the platform. Alternative you can download the codes from our https://wikifactory.com/+OttoDIY/
2. Compile error to Nano is really weird make sure you have the drivers installed
3. Easy to download that is why we no longer want to use github rather Wikifactory give a try and let me know if the problem persist there

You are welcome 
Camilo

**Comment by EddieMontana** [comment]
Camilo,
I got your message, thank you! I downloaded the Otto Plus files from the Wikifactory link that you provided, replaced all the libraries in the Arduino software and... BOOM! Suddenly everything started working, all the .ino files that I previously had issues with now work great. No errors of any kind. I'm sure other people may have the same issues... that's why I wanted to comment here so others could see the solution! Thanks again!
Eddie

**Comment by cparrapa** [comment]
Hi Eddie

thanks for the comment we really need more people like you in the Otto builder community (https://www.facebook.com/groups/ottodiy/)  to tell us constructive feedback if you find anything else in the codes do not hesitate to ask. Even do we stop promoting github for our files and trying to redirect all to wikifactory you can comment there to! but i guess takes time to people to catch up with a new platform even do is much easy to use.

Please take a look to the DIY (https://github.com/OttoDIY/DIY) repository and let me know if something also is not working for you.

Have a good day
Camilo
