### ISSUE TITLE
Where is the BOM file?

### ISSUE THREAD

**Issue by akohlsmith** [OttoDIY/PLUS#21]
The README.md mentions gathering all the hardware listed in the BOM file, but I don't see a BOM in this repo nor in the .zip file. The instructions are very Ikea-like in that it minimizes text which is helpful for worldwide use, but without a BOM file it is a sticking point.

**Comment by cparrapa** [comment]
Hi there
thanks just updated the readme and included the list of parts there
you are welcome  and hope to see your Otto creation!
