### ISSUE TITLE
BT commands do not respond

### ISSUE THREAD

**Issue by nicospomer** [OttoDIY/PLUS#22]
Hello,

I'm experiencing an issue with the APP (OttoDIYAPP_125.apk) and the code "OttoDIYAPP_125_baudrate9600.ino". I can see that the NANO is receiving data from the app as the RX led is enabled each time a button is pressed on the phone. When I check the serial port, I can see that a numbers are being sent from the App but just that, I didn't see any letter like "M", etc. I compiled the code using the libraries shared into the APP folder.
Do you have any idea about why the nano is not processing the information sent from the App?

Note: I'm testing Otto with USB and not with batteries. Could this be related with the issue?

Thank you!
Nico

**Comment by nicospomer** [comment]
Hi Camilo,
It's working now! I am using the code provided in that library.
I'm not sure if each button is doing the proper movement but now the nano is receiving data from the BT and the robot is acting! I need to do some additional test to ensure that all functions are working as expected.
Thank you so much!

**Comment by cparrapa** [comment]
Hi Nico
You are welcome! glad to help and happy to know it works!
Let me know if something else there in wikifactory ;)
Camilo
