### ISSUE TITLE
Error OTTO_FULL_MOUTH_HI.ino

### ISSUE THREAD

**Issue by UUSR** [OttoDIY/PLUS#6]
![screenshot_1](https://cloud.githubusercontent.com/assets/17599033/24777883/edcbceb0-1b27-11e7-9098-0aefcb482957.png)

**Comment by cparrapa** [comment]
Did you use the librarie for the matrix?

**Comment by cparrapa** [comment]
Hi David
Your error is related with calibration not Matrix, please create a new issue
