### ISSUE TITLE
bluetooth settings

### ISSUE THREAD

**Issue by damopinn** [OttoDIY/PLUS#9]
I can't find the settings so I can use otto+ with the zowi app.
things like baudrate name password, which I should set with the AT commands.

**Comment by stembotvn** [comment]
You need to change the name of HC06 to "Zowi" , please see my example for how to change HC06 name: 
https://github.com/stembotvn/OttoDIY_Vbot/tree/master/examples/HC06_BT_config

**Comment by zhisync** [comment]
Can I change to "Zowixxx", so I can control the other otto?
thanks.

**Comment by stembotvn** [comment]
Zowi app just detect bluetooth device named "Zowi", so we can not do that. Please use the OttoDIY app for easier experience.
